In [1]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import  cosine_similarity
import re

In [2]:
fooData = pd.read_csv('D:\\Projects\\Machine Learning\\FoodReccSystem\\fooddataset.csv')

In [3]:
fooData.head()

Food_ID                  Name        C_Type  Veg_Non  \
0        1   summer squash salad  Healthy Food      veg   
1        2  chicken minced salad  Healthy Food  non-veg   
2        3  sweet chilli almonds         Snack      veg   
3        4       tricolour salad  Healthy Food      veg   
4        5        christmas cake       Dessert      veg   

                                            Describe  
0  white balsamic vinegar, lemon juice, lemon rin...  
1  olive oil, chicken mince, garlic (minced), oni...  
2  almonds whole, egg white, curry leaves, salt, ...  
3  vinegar, honey/sugar, soy sauce, salt, garlic ...  
4  christmas dry fruits (pre-soaked), orange zest...

In [5]:
fooData.shape

(400, 5)

In [6]:
fooData.isnull().sum()

Food_ID     0
Name        0
C_Type      0
Veg_Non     0
Describe    0
dtype: int64

In [7]:
#NO null values found in the given data set

#combining all the feature to a list format
combinedFeatures = fooData['Name'] +' ' +fooData['C_Type'] +' ' +fooData['Veg_Non'] +' ' +fooData['Describe']

In [8]:
print(combinedFeatures)

0      summer squash salad Healthy Food veg white bal...
1      chicken minced salad Healthy Food non-veg oliv...
2      sweet chilli almonds Snack veg almonds whole, ...
3      tricolour salad Healthy Food veg vinegar, hone...
4      christmas cake Dessert veg christmas dry fruit...
                             ...                        
395    Kimchi Toast Korean veg  cream cheese, chopped...
396    Tacos de Gobernador (Shrimp, Poblano, and Chee...
397    Melted Broccoli Pasta With Capers and Anchovie...
398    Lemon-Ginger Cake with Pistachios Dessert non-...
399    Rosemary Roasted Vegetables Healthy Food veg k...
Length: 400, dtype: object


In [12]:
print(combinedFeatures[21])

baked namak para Snack veg whole wheat flour (atta) refined flour (maida) baking powder ghee salt carom seeds (ajwain)


In [9]:
# Assuming combinedFeatures is a list of strings
combinedFeatures = [feature.replace(',', '') for feature in combinedFeatures]

In [10]:
print(combinedFeatures)

['summer squash salad Healthy Food veg white balsamic vinegar lemon juice lemon rind red chillies garlic cloves (crushed) olive oil summer squash (zucchini) sea salt black pepper basil leaves', 'chicken minced salad Healthy Food non-veg olive oil chicken mince garlic (minced) onion salt black pepper carrot cabbage green onions sweet chilli sauce peanut butter ginger soy sauce fresh cilantro red pepper flakes (crushed) tarts', 'sweet chilli almonds Snack veg almonds whole egg white curry leaves salt sugar (fine grain) red chilli powder', 'tricolour salad Healthy Food veg vinegar honey/sugar soy sauce salt garlic cloves (minced) chilli pepper (sliced) green papaya carrot (peeled) cucumbers mint leaves toasted peanuts', 'christmas cake Dessert veg christmas dry fruits (pre-soaked) orange zest lemon zest jaggery syrup almond flour apple butter (softened) eggs', 'japanese curry arancini with barley salsa Japanese veg japanese curry sticky rice cheese inside rice barley salsa wasabi mayo red

In [13]:
print(combinedFeatures[21])

baked namak para Snack veg whole wheat flour (atta) refined flour (maida) baking powder ghee salt carom seeds (ajwain)


In [15]:
vectorizer = TfidfVectorizer()

In [16]:
featureVector = vectorizer.fit(combinedFeatures)

In [17]:
featureVector = vectorizer.transform(combinedFeatures)

Generating similaity matrix score using Cosine Similarity

In [18]:
similarity = cosine_similarity(featureVector)

In [20]:
print(similarity)

[[1.         0.17952959 0.08159817 ... 0.07412383 0.07384476 0.10275321]
 [0.17952959 1.         0.11949727 ... 0.10184851 0.06712536 0.15705625]
 [0.08159817 0.11949727 1.         ... 0.02060766 0.07078896 0.0144069 ]
 ...
 [0.07412383 0.10184851 0.02060766 ... 1.         0.03868736 0.05588566]
 [0.07384476 0.06712536 0.07078896 ... 0.03868736 1.         0.0037409 ]
 [0.10275321 0.15705625 0.0144069  ... 0.05588566 0.0037409  1.        ]]


Generating a list with all movie titles of the Dataset

In [21]:
Listallfood = fooData['Name'].tolist()

In [22]:
print(Listallfood)

['summer squash salad', 'chicken minced salad', 'sweet chilli almonds', 'tricolour salad', 'christmas cake', 'japanese curry arancini with barley salsa', 'chocolate nero cookies', 'lamb and chargrilled bell pepper soup', 'cream of almond soup', 'broccoli and almond soup', 'coconut lime quinoa salad', 'lemon honey glazed sous vide corn on the cob', 'watermelon and strawberry smoothie', 'peach, raspberry and nuts smoothie', 'almond and cranberry poha', 'almond and raw banana galawat', 'baked namakpara with roasted almond dip', 'grilled almond barfi', 'baked shankarpali ', 'baked multigrain murukku', 'apple rabdi', 'baked namak para', 'dates and nuts ladoo', 'green lentil dessert fudge', 'cashew nut cookies', 'almond pearls', 'hawaiin papaya salad', 'vegetable som tam salad', 'spinach and feta crepes', 'couscous with ratatouille - tangy tomato sauce', 'baked almond kofta', 'almond and amaranth ladoo', 'moong dal kiwi coconut soup', 'mixed berry & banana smoothie', 'banana walnut smoothie'

In [25]:
#for testing let us take ip = 'Chana Masala'

In [26]:
ip = 'Chana Masala'

In [27]:
#finding the closest match form the Listallfood to the ip

In [29]:
FindCloseMatch = difflib.get_close_matches(ip,Listallfood)

In [30]:
print(FindCloseMatch)

['Channa Masala', 'chicken masala']


In [31]:
CloseMatch  = FindCloseMatch[0]

In [32]:
print(CloseMatch)

Channa Masala


finding the index of the movie based on the Name(closeMatch)

In [35]:
index_of_food = fooData[fooData['Name']==CloseMatch]['Food_ID'].values[0]
print(index_of_food)

346


In [36]:
similarity_score = list(enumerate(similarity[index_of_food]))

In [37]:
print(similarity_score)

[(0, 0.0028175614609298864), (1, 0.019409818133869994), (2, 0.02121561711657686), (3, 0.0033905535434999774), (4, 0.0029452129685967263), (5, 0.0016517869692926816), (6, 0.016667740132916647), (7, 0.042809318305875824), (8, 0.003049838142329311), (9, 0.0034518097806928755), (10, 0.012955783948631663), (11, 0.010302788910100042), (12, 0.0035068416717748438), (13, 0.0021509718704834594), (14, 0.02113116620198186), (15, 0.04137487402948994), (16, 0.0032746620556624918), (17, 0.004586311456253349), (18, 0.06474794177462868), (19, 0.03592511054953451), (20, 0.0036832108848940787), (21, 0.01784056576591099), (22, 0.0030394566024422105), (23, 0.003216667723181257), (24, 0.012459109403149447), (25, 0.10692217440540161), (26, 0.0025760308111144755), (27, 0.0028586222956774347), (28, 0.1079504733957934), (29, 0.016011471492624437), (30, 0.050746263636701476), (31, 0.00341452897806305), (32, 0.0814814569415695), (33, 0.003279228926201669), (34, 0.0034661046591170667), (35, 0.0036052143566603196),

In [38]:
soreted_similar_movie = sorted(similarity_score,key =lambda x:x[1], reverse=True)

In [40]:
print(soreted_similar_movie)

[(346, 1.0), (342, 0.38913210972705903), (353, 0.3317679711770772), (347, 0.26067774193811627), (350, 0.2513885948838721), (348, 0.22800346645673125), (352, 0.21045681663717514), (161, 0.18986198251063585), (284, 0.18394711470920405), (315, 0.1709256705588392), (341, 0.16359257194785487), (363, 0.1623402374322733), (349, 0.15893625608480785), (259, 0.1529490011950334), (262, 0.14928643577885548), (152, 0.14375743138194103), (257, 0.14162507025566962), (38, 0.13995890965168992), (102, 0.13792278166376387), (332, 0.137644635377768), (101, 0.13594816541248358), (159, 0.13511336435181998), (180, 0.13495775345362704), (77, 0.1346293024239261), (333, 0.13346677684719416), (99, 0.1322415128725469), (345, 0.1303843989007101), (319, 0.13014244285975407), (296, 0.12950430592269904), (354, 0.1265073459797803), (351, 0.11859497198244309), (211, 0.11686773829948582), (362, 0.1164854427683589), (40, 0.11596577160175686), (335, 0.11548784314044067), (114, 0.11476758872319837), (198, 0.111662205946595

Printing all the names of the Suggested Foods

In [57]:
print('Suggested Foods are : ')
i=1
for food in soreted_similar_movie:
    index = food[0]
    

    title_from_index = fooData[fooData.Food_ID==index]['Name'].values[0]

    if(i<30):
        print(i, '.',title_from_index)
        i+=1

Suggested Foods are : 
1 . Channa Masala
2 . Mushroom Rice
3 . Hyakula
4 . Saag Alo 
5 . Jeera Alu
6 . Alo Tama Bodi
7 . Lamb Shashlik
8 . spanish fish fry
9 . strawberry quinoa pancakes
10 . Quinoa Bowl and Berries
11 . Cheese Naan
12 . Bao Bun 
13 . Tarka Daal
14 . ragi coconut ladoo (laddu)
15 . chicken masala
16 . prawn fried rice
17 . ragi oats ladoo (laddu)
18 . mixed salad with lotus root
19 . dahi chicken
20 . Mushroom Manchruian
21 . crispy herb chicken
22 . batter fish
23 . lotus leaf wrapped fried rice
24 . grilled lemon margarita
25 . Biryani
26 . spicy chicken masala
27 . Cucumber and Radish Salad
28 . Crispy Pakora
29 . tandoori fish tikka


IndexError: index 0 is out of bounds for axis 0 with size 0